Imports System.Collections.Generic
Imports System.Globalization
Imports Newtonsoft.Json

Public Class CustomCtrlCountry
    Inherits CustomCtrlMoedels

    Public Sub New()
        Me._countries = New Countries().GetSystemCountries()
        '  Dim _countries = New Countries()
        '  _countries.GetSystemCountries()

    End Sub

    Private _countries As SortedDictionary(Of Integer, String)
    Public Property Countries() As SortedDictionary(Of Integer, String)
        Get
            Return _countries
        End Get
        Set(ByVal value As SortedDictionary(Of Integer, String))
            _countries = value
        End Set
    End Property
End Class



Public Class Countries
    Public Shared Function GetCountries() As SortedDictionary(Of String, String)

        Dim countryList As New SortedDictionary(Of String, String)
        ' Iterate the Framework Cultures...
        For Each ci As CultureInfo In CultureInfo.GetCultures(CultureTypes.FrameworkCultures)
            Dim ri As RegionInfo
            Try
                ri = New RegionInfo(ci.Name)
            Catch
                ' If a RegionInfo object could not be created we don't want to use the CultureInfo
                '    for the country list.
                Continue For
            End Try
            ' Create new country dictionary entry.
            Dim newKeyValuePair As New KeyValuePair(Of String, String)(ri.EnglishName, ri.ThreeLetterISORegionName)

            ' If the country is not alreayd in the countryList add it...
            If Not countryList.ContainsKey(ri.EnglishName) Then
                countryList.Add(newKeyValuePair.Key, newKeyValuePair.Value)
            End If
        Next

        Return countryList
    End Function

    Public Function GetSystemCountries() As SortedDictionary(Of Integer, String)
        Dim _stscountry = New SortedDictionary(Of Integer, String)
        _stscountry.Add(1, "")
        _stscountry.Add(2, "AFGHANISTAN")
        _stscountry.Add(3, "ALBANIA")
        _stscountry.Add(4, "ALGERIA")
        _stscountry.Add(5, "AMERICAN SAMOA")
        _stscountry.Add(6, "ANDORRA")
        _stscountry.Add(7, "ANGOLA")
        _stscountry.Add(8, "ANGUILLA")
        _stscountry.Add(9, "ANTIGUA AND BARBUDA")
        _stscountry.Add(10, "ARGENTINA")
        _stscountry.Add(11, "ARMENIA")
        _stscountry.Add(12, "ARUBA")
        _stscountry.Add(13, "AUSTRALIA")
        _stscountry.Add(14, "AUSTRIA")
        _stscountry.Add(15, "AZERBAIJAN")
        _stscountry.Add(16, "BAHAMAS")
        _stscountry.Add(17, "BAHRAIN")
        _stscountry.Add(18, "BANGLADESH")
        _stscountry.Add(19, "BARBADOS")
        _stscountry.Add(20, "BELARUS")
        _stscountry.Add(21, "BELGIUM")
        _stscountry.Add(22, "BELIZE")
        _stscountry.Add(23, "BENIN")
        _stscountry.Add(24, "BERMUDA")
        _stscountry.Add(25, "BHUTAN")
        _stscountry.Add(26, "BOLIVIA")
        _stscountry.Add(27, "BONAIRE, SAINT EUSTATIUS AND SABA")
        _stscountry.Add(28, "BOSNIA & HERZEGOVINA")
        _stscountry.Add(29, "BOTSWANA")
        _stscountry.Add(30, "BOUVET ISLAND")
        _stscountry.Add(31, "BRAZIL")
        _stscountry.Add(32, "BRIT INDIAN OCN TERR")
        _stscountry.Add(33, "BRITISH OVERSEAS TERRITORIES CITIZEN")
        _stscountry.Add(34, "BRUNEI DARUSSALAM")
        _stscountry.Add(35, "BULGARIA")
        _stscountry.Add(36, "BURKINA FASO")
        _stscountry.Add(37, "BURUNDI")
        _stscountry.Add(38, "CABO VERDE")
        _stscountry.Add(39, "CAMBODIA")
        _stscountry.Add(40, "CAMEROON")
        _stscountry.Add(41, "CANADA")
        _stscountry.Add(42, "CAPE VERDE")
        _stscountry.Add(43, "CAYMAN ISLANDS")
        _stscountry.Add(44, "CENTRAL AFRICAN REP")
        _stscountry.Add(45, "CHAD")
        _stscountry.Add(46, "CHILE")
        _stscountry.Add(47, "CHINA")
        _stscountry.Add(48, "CHRISTMAS ISLAND")
        _stscountry.Add(49, "COCOS (KEELING) ISL")
        _stscountry.Add(50, "COLOMBIA")
        _stscountry.Add(51, "COMOROS")
        _stscountry.Add(52, "CONGO")
        _stscountry.Add(53, "COOK ISLANDS")
        _stscountry.Add(54, "COSTA RICA")
        _stscountry.Add(55, "COTE D'IVOIRE")
        _stscountry.Add(56, "CROATIA")
        _stscountry.Add(57, "CUBA")
        _stscountry.Add(58, "CURACAO")
        _stscountry.Add(59, "CYPRUS")
        _stscountry.Add(60, "CZECH REPUBLIC")
        _stscountry.Add(61, "DENMARK")
        _stscountry.Add(62, "DJIBOUTI")
        _stscountry.Add(63, "DOMINICA")
        _stscountry.Add(64, "DOMINICAN REPUBLIC")
        _stscountry.Add(65, "ECUADOR")
        _stscountry.Add(66, "EGYPT")
        _stscountry.Add(67, "EL SALVADOR")
        _stscountry.Add(68, "ENGLAND")
        _stscountry.Add(69, "EQUATORIAL GUINEA")
        _stscountry.Add(70, "ERITREA")
        _stscountry.Add(71, "ESTONIA")
        _stscountry.Add(72, "ETHIOPIA")
        _stscountry.Add(73, "FALKLAND ISLANDS")
        _stscountry.Add(74, "FAROE ISLANDS")
        _stscountry.Add(75, "FIJI")
        _stscountry.Add(76, "FINLAND")
        _stscountry.Add(77, "FRANCE")
        _stscountry.Add(78, "FRENCH GUIANA")
        _stscountry.Add(79, "FRENCH POLYNESIA")
        _stscountry.Add(80, "FYR MACEDONIA")
        _stscountry.Add(81, "GABON")
        _stscountry.Add(82, "GAMBIA")
        _stscountry.Add(83, "GAZA STRIP")
        _stscountry.Add(84, "GEORGIA")
        _stscountry.Add(85, "GEORGIA/SANDWICH ISL")
        _stscountry.Add(86, "GERMANY")
        _stscountry.Add(87, "GHANA")
        _stscountry.Add(88, "GIBRALTAR")
        _stscountry.Add(89, "GREECE")
        _stscountry.Add(90, "GREENLAND")
        _stscountry.Add(91, "GRENADA")
        _stscountry.Add(92, "GUADELOUPE")
        _stscountry.Add(93, "GUAM")
        _stscountry.Add(94, "GUATEMALA")
        _stscountry.Add(95, "GUERNSEY")
        _stscountry.Add(96, "GUINEA")
        _stscountry.Add(97, "GUINEA-BISSAU")
        _stscountry.Add(98, "GUYANA")
        _stscountry.Add(99, "HAITI")
        _stscountry.Add(100, "HEARD & MCDONALD ISL")
        _stscountry.Add(101, "HONDURAS")
        _stscountry.Add(102, "HONG KONG SAR")
        _stscountry.Add(103, "HUNGARY")
        _stscountry.Add(104, "ICELAND")
        _stscountry.Add(105, "INDIA")
        _stscountry.Add(106, "INDONESIA")
        _stscountry.Add(107, "IRAN")
        _stscountry.Add(108, "IRAQ")
        _stscountry.Add(109, "IRELAND, REPUBLIC OF")
        _stscountry.Add(110, "ISLE OF MAN")
        _stscountry.Add(111, "ISRAEL")
        _stscountry.Add(112, "ITALY")
        _stscountry.Add(113, "JAMAICA")
        _stscountry.Add(114, "JAPAN")
        _stscountry.Add(115, "JERSEY")
        _stscountry.Add(116, "JORDAN")
        _stscountry.Add(117, "KAZAKHSTAN")
        _stscountry.Add(118, "KENYA")
        _stscountry.Add(119, "KIRIBATI")
        _stscountry.Add(120, "KOREA, NORTH")
        _stscountry.Add(121, "KOREA, SOUTH")
        _stscountry.Add(122, "KOSOVO")
        _stscountry.Add(123, "KUWAIT")
        _stscountry.Add(124, "KYRGYZSTAN")
        _stscountry.Add(125, "LAO PEOPLES DEM REP")
        _stscountry.Add(126, "LATVIA")
        _stscountry.Add(127, "LEBANON")
        _stscountry.Add(128, "LESOTHO")
        _stscountry.Add(129, "LIBERIA")
        _stscountry.Add(130, "LIBYA")
        _stscountry.Add(131, "LIECHTENSTEIN")
        _stscountry.Add(132, "LITHUANIA")
        _stscountry.Add(133, "LUXEMBOURG")
        _stscountry.Add(134, "MACAU SPCL ADMIN RGNv")
        _stscountry.Add(135, "MADAGASCAR")
        _stscountry.Add(136, "MALAWI")
        _stscountry.Add(137, "MALAYSIA")
        _stscountry.Add(138, "MALDIVES")
        _stscountry.Add(139, "MALI")
        _stscountry.Add(140, "MALTA")
        _stscountry.Add(141, "MARSHALL ISLANDS")
        _stscountry.Add(142, "MARTINIQUE")
        _stscountry.Add(143, "MAURITANIA")
        _stscountry.Add(144, "MAURITIUS")
        _stscountry.Add(145, "MAYOTTE")
        _stscountry.Add(146, "MEXICO")
        _stscountry.Add(147, "MICRONESIA")
        _stscountry.Add(148, "MOLDOVA")
        _stscountry.Add(149, "MONACO")
        _stscountry.Add(150, "MONGOLIA")
        _stscountry.Add(151, "MONTENEGRO")
        _stscountry.Add(152, "MONTSERRAT")
        _stscountry.Add(153, "MOROCCO")
        _stscountry.Add(154, "MOZAMBIQUE")
        _stscountry.Add(155, "MYANMAR")
        _stscountry.Add(156, "NAMIBIA")
        _stscountry.Add(157, "NAURU")
        _stscountry.Add(158, "NEPAL")
        _stscountry.Add(159, "NETHERLANDS")
        _stscountry.Add(160, "NEW CALEDONIA")
        _stscountry.Add(161, "NEW GUINEA")
        _stscountry.Add(162, "NEW HEBRIDES")
        _stscountry.Add(163, "NEW ZEALAND")
        _stscountry.Add(164, "NICARAGUA")
        _stscountry.Add(165, "NIGER")
        _stscountry.Add(166, "NIGERIA")
        _stscountry.Add(167, "NIUE")
        _stscountry.Add(168, "NORFOLK ISLAND")
        _stscountry.Add(169, "NORTHERN IRELAND")
        _stscountry.Add(170, "NORTHERN MARIANA ISL")
        _stscountry.Add(171, "NORWAY")
        _stscountry.Add(172, "OMAN")
        _stscountry.Add(173, "PAKISTAN")
        _stscountry.Add(174, "PALAU")
        _stscountry.Add(175, "PALESTINIAN AUTHORTY")
        _stscountry.Add(176, "PANAMA")
        _stscountry.Add(177, "PAPUA NEW GUINEA")
        _stscountry.Add(178, "PARAGUAY")
        _stscountry.Add(179, "PERU")
        _stscountry.Add(180, "PHILIPPINES")
        _stscountry.Add(181, "PITCAIRN")
        _stscountry.Add(182, "POLAND")
        _stscountry.Add(183, "PORTUGAL")
        _stscountry.Add(184, "PUERTO RICO")
        _stscountry.Add(185, "QATAR")
        _stscountry.Add(186, "REUNION")
        _stscountry.Add(187, "ROMANIA")
        _stscountry.Add(188, "RUSSIAN FEDERATION")
        _stscountry.Add(189, "RWANDA")
        _stscountry.Add(190, "SAINT BARTHELEMY")
        _stscountry.Add(191, "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA")
        _stscountry.Add(192, "SAINT LUCIA")
        _stscountry.Add(193, "SAINT MARTIN")
        _stscountry.Add(194, "SAMOA")
        _stscountry.Add(195, "SAN MARINO")
        _stscountry.Add(196, "SAO TOME & PRINCIPE")
        _stscountry.Add(197, "SAUDI ARABIA")
        _stscountry.Add(198, "SCOTLAND")
        _stscountry.Add(199, "SENEGAL")
        _stscountry.Add(200, "SERBIA")
        _stscountry.Add(201, "SEYCHELLES")
        _stscountry.Add(202, "SIERRA LEONE")
        _stscountry.Add(203, "SINGAPORE")
        _stscountry.Add(204, "SINT MAARTEN (DUTCH PART)")
        _stscountry.Add(205, "SLOVAK REPUBLIC")
        _stscountry.Add(206, "SLOVENIA")
        _stscountry.Add(207, "SOLOMON ISLANDS")
        _stscountry.Add(208, "SOMALIA")
        _stscountry.Add(209, "SOUTH AFRICA")
        _stscountry.Add(210, "SOUTH SUDAN")
        _stscountry.Add(211, "SPAIN")
        _stscountry.Add(212, "SRI LANKA")
        _stscountry.Add(213, "ST HELENA")
        _stscountry.Add(214, "ST KITTS AND NEVIS")
        _stscountry.Add(215, "ST PIERRE & MIQUELON")
        _stscountry.Add(216, "ST VINCENT/GRENADINE")
        _stscountry.Add(217, "SUDAN")
        _stscountry.Add(218, "SURINAME")
        _stscountry.Add(219, "SVALBARD & JAN MAYEN")
        _stscountry.Add(220, "SWAZILAND")
        _stscountry.Add(221, "SWEDEN")
        _stscountry.Add(222, "SWITZERLAND")
        _stscountry.Add(223, "SYRIA")
        _stscountry.Add(224, "TAIWAN")
        _stscountry.Add(225, "TAJIKISTAN")
        _stscountry.Add(226, "TANZANIA")
        _stscountry.Add(227, "THAILAND")
        _stscountry.Add(228, "TIMOR, EAST")
        _stscountry.Add(229, "TIMOR-LESTE")
        _stscountry.Add(230, "TOGO")
        _stscountry.Add(231, "TOKELAU")
        _stscountry.Add(232, "TONGA")
        _stscountry.Add(233, "TRINIDAD AND TOBAGO")
        _stscountry.Add(234, "TUNISIA")
        _stscountry.Add(235, "TURKEY")
        _stscountry.Add(236, "TURKMENISTAN")
        _stscountry.Add(237, "TURKS AND CAICOS ISL")
        _stscountry.Add(238, "TUVALU")
        _stscountry.Add(239, "U.S. MINOR ISLANDS")
        _stscountry.Add(240, "UGANDA")
        _stscountry.Add(241, "UKRAINE")
        _stscountry.Add(242, "UNITED ARAB EMIRATES")
        _stscountry.Add(243, "UNITED KINGDOM")
        _stscountry.Add(244, "UNITED STATES")
        _stscountry.Add(245, "URUGUAY")
        _stscountry.Add(246, "UZBEKISTAN")
        _stscountry.Add(247, "VANUATU")
        _stscountry.Add(248, "VATICAN CITY STATE")
        _stscountry.Add(249, "VENEZUELA")
        _stscountry.Add(250, "VIETNAM")
        _stscountry.Add(251, "VIRGIN ISLANDS (U.S)")
        _stscountry.Add(252, "VIRGIN ISLNDS (BRIT)")
        _stscountry.Add(253, "WALES")
        _stscountry.Add(254, "WALLIS & FUTUNA ISL")
        _stscountry.Add(255, "WEST BANK")
        _stscountry.Add(256, "YEMEN")
        _stscountry.Add(257, "YUGOSLAVIA")
        _stscountry.Add(258, "ZAIRE")
        _stscountry.Add(259, "ZAMBIA")
        _stscountry.Add(260, "ZIMBABWE")
        Return _stscountry
    End Function

End Class
