Public Class CustomCtrlPassportCountry
    Inherits CustomCtrlMoedels
    Private _countries As SortedDictionary(Of Integer, String)
    Public Property Countries() As SortedDictionary(Of Integer, String)
        Get
            Return _countries
        End Get
        Set(ByVal value As SortedDictionary(Of Integer, String))
            _countries = value
        End Set
    End Property
    Public Sub New()
        Me._countries = New SortedDictionary(Of Integer, String)
        Me._countries.Add(1, "")
        Me._countries.Add(2, "AFGHANISTAN - AFG")
        Me._countries.Add(3, "ALBANIA - ALB")
        Me._countries.Add(4, "ALGERIA - DZA")
        Me._countries.Add(5, "AMERICAN SAMOA - ASM")
        Me._countries.Add(6, "ANDORRA - AND")
        Me._countries.Add(7, "ANGOLA - AGO")
        Me._countries.Add(8, "ANGUILLA - AIA")
        Me._countries.Add(9, "ANTIGUA AND BARBUDA - ATG")
        Me._countries.Add(10, "ARGENTINA - ARG")
        Me._countries.Add(11, "ARMENIA - ARM")
        Me._countries.Add(12, "ARUBA - ABW")
        Me._countries.Add(13, "AUSTRALIA - AUS")
        Me._countries.Add(14, "AUSTRIA - AUT")
        Me._countries.Add(15, "AZERBAIJAN - AZE")
        Me._countries.Add(16, "BAHAMAS - BHS")
        Me._countries.Add(17, "BAHRAIN - BHR")
        Me._countries.Add(18, "BANGLADESH - BGD")
        Me._countries.Add(19, "BARBADOS - BRB")
        Me._countries.Add(20, "BELARUS - BLR")
        Me._countries.Add(21, "BELGIUM - BEL")
        Me._countries.Add(22, "BELIZE - BLZ")
        Me._countries.Add(23, "BENIN - BEN")
        Me._countries.Add(24, "BERMUDA - BMU")
        Me._countries.Add(25, "BHUTAN - BTN")
        Me._countries.Add(26, "BOLIVIA - BOL")
        Me._countries.Add(27, "BONAIRE, SAINT EUSTATIUS AND SABA - BES")
        Me._countries.Add(28, "BOSNIA AND HERZEGOVINA - BIH")
        Me._countries.Add(29, "BOTSWANA - BWA")
        Me._countries.Add(30, "BRAZIL - BRA")
        Me._countries.Add(31, "BRUNEI DARUSSALAM - BRN")
        Me._countries.Add(32, "BULGARIA - BGR")
        Me._countries.Add(33, "BURKINA FASO - BFA")
        Me._countries.Add(34, "BURMA (MYANMAR) - MMR")
        Me._countries.Add(35, "BURUNDI - BDI")
        Me._countries.Add(36, "CABO VERDE - CPV")
        Me._countries.Add(37, "CAMBODIA - KHM")
        Me._countries.Add(38, "CAMEROON - CMR")
        Me._countries.Add(39, "CANADA - CAN")
        Me._countries.Add(40, "CAYMAN ISLANDS - CYM")
        Me._countries.Add(41, "CENTRAL AFRICAN REPUBLIC - CAF")
        Me._countries.Add(42, "CHAD - TCD")
        Me._countries.Add(43, "CHILE - CHL")
        Me._countries.Add(44, "CHINA - CHN")
        Me._countries.Add(45, "COLOMBIA - COL")
        Me._countries.Add(46, "COMOROS - COM")
        Me._countries.Add(47, "CONGO - COG")
        Me._countries.Add(48, "CONGO, DEMOCRATIC REPUBLIC OF THE - COD")
        Me._countries.Add(49, "COOK ISLANDS - COK")
        Me._countries.Add(50, "COSTA RICA - CRI")
        Me._countries.Add(51, "COTE D'IVOIRE - CIV")
        Me._countries.Add(52, "CROATIA - HRV")
        Me._countries.Add(53, "CUBA - CUB")
        Me._countries.Add(54, "CURACAO - CUW")
        Me._countries.Add(55, "CYPRUS - CYP")
        Me._countries.Add(56, "CZECH REPUBLIC - CZE")
        Me._countries.Add(57, "DENMARK - DNK")
        Me._countries.Add(58, "DJIBOUTI - DJI")
        Me._countries.Add(59, "DOMINICA - DMA")
        Me._countries.Add(60, "DOMINICAN REPUBLIC - DOM")
        Me._countries.Add(61, "EAST TIMOR - TMP")
        Me._countries.Add(62, "ECUADOR - ECU")
        Me._countries.Add(63, "EGYPT - EGY")
        Me._countries.Add(64, "EL SALVADOR - SLV")
        Me._countries.Add(65, "EQUATORIAL GUINEA - GNQ")
        Me._countries.Add(66, "ERITREA - ERI")
        Me._countries.Add(67, "ESTONIA - EST")
        Me._countries.Add(68, "ETHIOPIA - ETH")
        Me._countries.Add(69, "FALKLAND ISLANDS (MALVINAS) - FLK")
        Me._countries.Add(70, "FIJI - FJI")
        Me._countries.Add(71, "FINLAND - FIN")
        Me._countries.Add(72, "FRANCE - FRA")
        Me._countries.Add(73, "FRENCH GUIANA - GUF")
        Me._countries.Add(74, "FRENCH POLYNESIA - PYF")
        Me._countries.Add(75, "GABON - GAB")
        Me._countries.Add(76, "GAMBIA - GMB")
        Me._countries.Add(77, "GEORGIA - GEO")
        Me._countries.Add(78, "GERMANY - D")
        Me._countries.Add(79, "GHANA - GHA")
        Me._countries.Add(80, "GIBRALTAR - GIB")
        Me._countries.Add(81, "GREECE - GRC")
        Me._countries.Add(82, "GREENLAND - GRL")
        Me._countries.Add(83, "GRENADA - GRD")
        Me._countries.Add(84, "GUADELOUPE - GLP")
        Me._countries.Add(85, "GUAM - GUM")
        Me._countries.Add(86, "GUATEMALA - GTM")
        Me._countries.Add(87, "GUINEA - GIN")
        Me._countries.Add(88, "GUINEA-BISSAU - GNB")
        Me._countries.Add(89, "GUYANA - GUY")
        Me._countries.Add(90, "HAITI - HTI")
        Me._countries.Add(91, "HONDURAS - HND")
        Me._countries.Add(92, "HONG KONG SAR - HKG")
        Me._countries.Add(93, "HUNGARY - HUN")
        Me._countries.Add(94, "ICELAND - ISL")
        Me._countries.Add(95, "INDIA - IND")
        Me._countries.Add(96, "INDONESIA - IDN")
        Me._countries.Add(97, "IRAN, ISLAMIC REPUBLIC Of - IRN")
        Me._countries.Add(98, "IRAQ - IRQ")
        Me._countries.Add(99, "IRELAND - IRL")
        Me._countries.Add(100, "ISRAEL - ISR")
        Me._countries.Add(101, "ITALY - ITA")
        Me._countries.Add(102, "JAMAICA - JAM")
        Me._countries.Add(103, "JAPAN - JPN")
        Me._countries.Add(104, "JORDAN - JOR")
        Me._countries.Add(105, "KAZAKHSTAN - KAZ")
        Me._countries.Add(106, "KENYA - KEN")
        Me._countries.Add(107, "KIRIBATI - KIR")
        Me._countries.Add(108, "KOREA, DEMOCRATIC PEOPLES REPUBLIC Of (NORTH) - PRK")
        Me._countries.Add(109, "KOREA, REPUBLIC Of (SOUTH) - KOR")
        Me._countries.Add(110, "KOSOVO - RKS")
        Me._countries.Add(111, "KUWAIT - KWT")
        Me._countries.Add(112, "KYRGYZSTAN - KGZ")
        Me._countries.Add(113, "LAO PEOPLES DEMOCRATIC REPUBLIC - LAO")
        Me._countries.Add(114, "LATVIA - LVA")
        Me._countries.Add(115, "LEBANON - LBN")
        Me._countries.Add(116, "LESOTHO - LSO")
        Me._countries.Add(117, "LIBERIA - LBR")
        Me._countries.Add(118, "LIBYA - LBY")
        Me._countries.Add(119, "LIECHTENSTEIN - LIE")
        Me._countries.Add(120, "LITHUANIA - LTU")
        Me._countries.Add(121, "LUXEMBOURG - LUX")
        Me._countries.Add(122, "MACAU SAR - MAC")
        Me._countries.Add(123, "MACEDONIA, FORMER YUGOSLAV REPUBLIC OF - MKD")
        Me._countries.Add(124, "MADAGASCAR - MDG")
        Me._countries.Add(125, "MALAWI - MWI")
        Me._countries.Add(126, "MALAYSIA - MYS")
        Me._countries.Add(127, "MALDIVES - MDV")
        Me._countries.Add(128, "MALI - MLI")
        Me._countries.Add(129, "MALTA - MLT")
        Me._countries.Add(130, "MARSHALL ISLANDS - MHL")
        Me._countries.Add(131, "MARTINIQUE - MTQ")
        Me._countries.Add(132, "MAURITANIA - MRT")
        Me._countries.Add(133, "MAURITIUS - MUS")
        Me._countries.Add(134, "MEXICO - MEX")
        Me._countries.Add(135, "MICRONESIA, FEDERATED STATES OF - FSM")
        Me._countries.Add(136, "MOLDOVA, REPUBLIC OF - MDA")
        Me._countries.Add(137, "MONACO - MCO")
        Me._countries.Add(138, "MONGOLIA - MNG")
        Me._countries.Add(139, "MONTENEGRO - MNE")
        Me._countries.Add(140, "MONTSERRAT - MSR")
        Me._countries.Add(141, "MOROCCO - MAR")
        Me._countries.Add(142, "MOZAMBIQUE - MOZ")
        Me._countries.Add(143, "NAMIBIA - NAM")
        Me._countries.Add(144, "NAURU - NRU")
        Me._countries.Add(145, "NEPAL - NPL")
        Me._countries.Add(146, "NETHERLANDS - NLD")
        Me._countries.Add(147, "NETHERLANDS ANTILLES - ANT")
        Me._countries.Add(148, "NEW CALEDONIA - NCL")
        Me._countries.Add(149, "NEW ZEALAND - NZL")
        Me._countries.Add(150, "NICARAGUA - NIC")
        Me._countries.Add(151, "NIGER - NER")
        Me._countries.Add(152, "NIGERIA - NGA")
        Me._countries.Add(153, "NIUE - NIU")
        Me._countries.Add(154, "NORWAY - NOR")
        Me._countries.Add(155, "OMAN - OMN")
        Me._countries.Add(156, "PAKISTAN - PAK")
        Me._countries.Add(157, "PALAU - PLW")
        Me._countries.Add(158, "PALESTINIAN AUTHORITY - PSE")
        Me._countries.Add(159, "PANAMA - PAN")
        Me._countries.Add(160, "PAPUA NEW GUINEA - PNG")
        Me._countries.Add(161, "PARAGUAY - PRY")
        Me._countries.Add(162, "PERU - PER")
        Me._countries.Add(163, "PHILIPPINES - PHL")
        Me._countries.Add(164, "PITCAIRN - PCN")
        Me._countries.Add(165, "POLAND - POL")
        Me._countries.Add(166, "PORTUGAL - PRT")
        Me._countries.Add(167, "PUERTO RICO - PRI")
        Me._countries.Add(168, "QATAR - QAT")
        Me._countries.Add(169, "REUNION - REU")
        Me._countries.Add(170, "ROMANIA - ROU")
        Me._countries.Add(171, "ROMANIA PRE 1/2/2002 - ROM")
        Me._countries.Add(172, "RUSSIAN FEDERATION - RUS")
        Me._countries.Add(173, "RWANDA - RWA")
        Me._countries.Add(174, "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA - SHN")
        Me._countries.Add(175, "SAINT KITTS AND NEVIS - KNA")
        Me._countries.Add(176, "SAINT LUCIA - LCA")
        Me._countries.Add(177, "SAINT VINCENT AND THE GRENADINES - VCT")
        Me._countries.Add(178, "SAMOA - WSM")
        Me._countries.Add(179, "SAN MARINO - SMR")
        Me._countries.Add(180, "SAO TOME AND PRINCIPE - STP")
        Me._countries.Add(181, "SAUDI ARABIA - SAU")
        Me._countries.Add(182, "SENEGAL - SEN")
        Me._countries.Add(183, "SERBIA - SRB")
        Me._countries.Add(184, "SERBIA AND MONTENEGRO - SCG")
        Me._countries.Add(185, "SEYCHELLES - SYC")
        Me._countries.Add(186, "SIERRA LEONE - SLE")
        Me._countries.Add(187, "SINGAPORE - SGP")
        Me._countries.Add(188, "SINT MAARTEN (DUTCH PART) - SXM")
        Me._countries.Add(189, "SLOVAK REPUBLIC - SVK")
        Me._countries.Add(190, "SLOVENIA - SVN")
        Me._countries.Add(191, "SOLOMON ISLANDS - SLB")
        Me._countries.Add(192, "SOMALIA - SOM")
        Me._countries.Add(193, "SOUTH AFRICA - ZAF")
        Me._countries.Add(194, "SOUTH SUDAN - SSD")
        Me._countries.Add(195, "SPAIN - ESP")
        Me._countries.Add(196, "SRI LANKA - LKA")
        Me._countries.Add(197, "SUDAN - SDN")
        Me._countries.Add(198, "SURINAME - SUR")
        Me._countries.Add(199, "SWAZILAND - SWZ")
        Me._countries.Add(200, "SWEDEN - SWE")
        Me._countries.Add(201, "SWITZERLAND - CHE")
        Me._countries.Add(202, "SYRIAN ARAB REPUBLIC - SYR")
        Me._countries.Add(203, "TAIWAN - TWN")
        Me._countries.Add(204, "TAJIKISTAN - TJK")
        Me._countries.Add(205, "TANZANIA, UNITED REPUBLIC OF - TZA")
        Me._countries.Add(206, "THAILAND - THA")
        Me._countries.Add(207, "TIMOR-LESTE - TLS")
        Me._countries.Add(208, "TOGO - TGO")
        Me._countries.Add(209, "TOKELAU - TKL")
        Me._countries.Add(210, "TONGA - TON")
        Me._countries.Add(211, "TRINIDAD AND TOBAGO - TTO")
        Me._countries.Add(212, "TUNISIA - TUN")
        Me._countries.Add(213, "TURKEY - TUR")
        Me._countries.Add(214, "TURKMENISTAN - TKM")
        Me._countries.Add(215, "TURKS AND CAICOS ISLANDS - TCA")
        Me._countries.Add(216, "TUVALU - TUV")
        Me._countries.Add(217, "UGANDA - UGA")
        Me._countries.Add(218, "UKRAINE - UKR")
        Me._countries.Add(219, "UNITED ARAB EMIRATES - ARE")
        Me._countries.Add(220, "UNITED KINGDOM - BRITISH CITIZEN - GBR")
        Me._countries.Add(221, "UNITED KINGDOM - BRITISH NATIONAL (OVERSEAS) - GBN")
        Me._countries.Add(222, "UNITED KINGDOM - BRITISH OVERSEAS CITIZEN - GBO")
        Me._countries.Add(223, "UNITED KINGDOM - BRITISH OVERSEAS TERRITORIES CITIZEN - GBD")
        Me._countries.Add(224, "UNITED STATES - USA")
        Me._countries.Add(225, "URUGUAY - URY")
        Me._countries.Add(226, "UZBEKISTAN - UZB")
        Me._countries.Add(227, "VANUATU - VUT")
        Me._countries.Add(228, "VATICAN CITY STATE (HOLY SEE) - VAT")
        Me._countries.Add(229, "VENEZUELA - VEN")
        Me._countries.Add(230, "VIET NAM - VNM")
        Me._countries.Add(231, "VIRGIN ISLANDS (BRITISH) - VGB")
        Me._countries.Add(232, "YEMEN - YEM")
        Me._countries.Add(233, "YUGOSLAVIA - YUG")
        Me._countries.Add(234, "ZAIRE - ZAR")
        Me._countries.Add(235, "ZAMBIA - ZMB")
        Me._countries.Add(236, "ZIMBABWE - ZWE")

    End Sub
End Class
